import {
  LEGAL_LAST_UPDATED,
  LEGAL_VERSION,
  type LegalDocument,
  p,
  ul,
  section,
} from './types';

export const TERMS: LegalDocument = {
  id: 'terms',
  version: LEGAL_VERSION,
  lastUpdated: LEGAL_LAST_UPDATED,
  path: '/terms-of-service',
  title: 'FlacronCV Terms of Service',
  description:
    'These Terms of Service govern your access to and use of FlacronCV, including its website, application, AI-powered CV builder, Cover Letter tools, ATS tools, templates, Job Tracker, subscriptions, document exports, and related services.',
  preamble: [
    p(
      'These Terms of Service govern your access to and use of FlacronCV, including its website, application, AI-powered CV builder, Cover Letter tools, ATS tools, templates, Job Tracker, subscriptions, document exports, and related services.',
    ),
    p('FlacronCV is operated by:'),
    p('Flacron Enterprises'),
    p('410 E 95th St'),
    p('Brooklyn, NY 11212'),
    p('United States'),
    p('Phone: 929-990-1182'),
    p('FlacronCV Email: contact@flacroncv.com'),
    p('Parent Company Email: Contact@flacronenterprises.com'),
    p('Powered by Flacron Engine'),
    p(
      'By creating an account, purchasing a subscription, starting a trial, or using FlacronCV, you agree to these Terms.',
    ),
    p('If you do not agree, do not use FlacronCV.'),
  ],
  sections: [
    section('1', '1. Description of FlacronCV', [
      p('FlacronCV is an AI-powered career-document platform.'),
      p('Features may include:'),
      ul([
        'CV builder',
        'Résumé builder',
        'AI Writing Assistant',
        'Professional templates',
        'Cover Letter Builder',
        'ATS optimization',
        'ATS compatibility scoring',
        'Job-description analysis',
        'Role-based suggestions',
        'Multilingual tools',
        'Job Tracker',
        'PDF export',
        'DOCX export',
        'AI-generated career content',
      ]),
      p('Features may change over time.'),
    ]),
    section('2', '2. No Employment Guarantee', [
      p('FlacronCV does not guarantee:'),
      ul([
        'Employment',
        'Interviews',
        'Job offers',
        'Recruiter responses',
        'ATS acceptance',
        'ATS ranking',
        'Salary increases',
        'Career advancement',
        'Successful applications',
      ]),
      p(
        'Hiring decisions are made independently by employers, recruiters, hiring managers, applicant-tracking-system operators, and other third parties.',
      ),
    ]),
    section('3', '3. ATS Disclaimer', [
      p(
        'ATS scores, keyword suggestions, optimization recommendations, and compatibility indicators are estimates and informational tools.',
      ),
      p("FlacronCV cannot know or guarantee how a specific employer's applicant-tracking system will:"),
      ul([
        'Parse a document',
        'Score a CV',
        'Rank an applicant',
        'Filter an applicant',
        'Display a CV',
        'Make recommendations',
      ]),
      p(
        'Different employers may use different systems, rules, configurations, and hiring processes.',
      ),
    ]),
    section('4', '4. Eligibility', [
      p('You may use FlacronCV only if:'),
      ul([
        'You have legal capacity to enter into a binding agreement',
        'You satisfy applicable age requirements',
        'Your use is lawful in your jurisdiction',
        'You are not prohibited from using the service under applicable law',
      ]),
    ]),
    section('5', '5. User Accounts', [
      p('You agree to:'),
      ul([
        'Provide accurate account information',
        'Maintain accurate information',
        'Protect your password',
        'Protect access to your email',
        'Notify us of unauthorized access',
        'Accept responsibility for activity under your account',
      ]),
      p('You may not:'),
      ul([
        'Sell your account',
        'Improperly transfer your account',
        'Circumvent account restrictions',
        'Circumvent subscription limits',
        'Circumvent Free Plan restrictions',
        'Impersonate another person',
        'Create accounts for fraudulent purposes',
      ]),
    ]),
    section('6', '6. Free Plan', [
      p('FlacronCV may offer a limited Free Plan.'),
      p('The Free Plan may currently include limits such as:'),
      ul(['5 CVs', '1 Cover Letter', '5 AI Credits', '2 Exports']),
      p('The current allowance displayed in the application controls.'),
      p('The Free Plan is intended for legitimate eligible users.'),
      p(
        'Creating multiple accounts or using technical methods to repeatedly obtain additional Free Plan allowances is prohibited.',
      ),
      p('This includes attempts to circumvent Free Plan restrictions through:'),
      ul([
        'Multiple accounts',
        'Repeated email addresses',
        'Device manipulation',
        'Automated account creation',
        'Cookie deletion',
        'Browser-storage manipulation',
        'API manipulation',
        'Fraudulent identity information',
      ]),
      p(
        'FlacronCV may use reasonable account, device, network, usage, and security signals to enforce Free Plan eligibility.',
      ),
      p('Free Plan limits and availability may change.'),
    ]),
    section('7', '7. Paid Plans', [
      p('FlacronCV may offer paid subscription plans including:'),
      p('Pro Plan'),
      p('Current displayed monthly price:'),
      p('$29.99/month'),
      p('Enterprise Plan'),
      p('Current displayed monthly price:'),
      p('$99.99/month'),
      p('Annual pricing may also be offered.'),
      p(
        'The exact price, billing period, trial terms, features, limits, and applicable taxes displayed at checkout control the transaction.',
      ),
    ]),
    section('8', '8. Free Trials', [
      p('FlacronCV may offer promotional free trials.'),
      p('Current offers may include a:'),
      p('7-day free trial'),
      p('Trial availability may be limited to eligible users.'),
      p('A user may not repeatedly create accounts to receive additional promotional trials.'),
      p(
        'If a trial converts automatically into a paid subscription, the price, billing frequency, trial expiration date, and cancellation terms must be disclosed before the user authorizes the subscription.',
      ),
    ]),
    section('9', '9. Recurring Billing', [
      p('Paid subscriptions may renew automatically unless canceled.'),
      p(
        'By purchasing a recurring subscription, you authorize the applicable payment provider to charge the stated subscription fee and applicable taxes at the agreed billing interval until cancellation.',
      ),
    ]),
    section('10', '10. Cancellation', [
      p('Users should be able to manage or cancel subscriptions through:'),
      p('Settings → Billing → Manage Subscription'),
      p('or through an authorized payment-provider portal where available.'),
      p(
        'Unless otherwise stated or required by law, cancellation ordinarily prevents the next renewal and does not immediately terminate access already paid for.',
      ),
    ]),
    section('11', '11. Refunds', [
      p(
        'Refund eligibility is governed by the FlacronCV Refund & Cancellation Policy and applicable law.',
      ),
    ]),
    section('12', '12. AI-Generated Content', [
      p('FlacronCV uses artificial intelligence.'),
      p('AI-generated content may:'),
      ul([
        'Contain errors',
        'Misinterpret information',
        'Be incomplete',
        'Produce unexpected wording',
        'Include inappropriate suggestions',
        'Fail to reflect your actual qualifications',
        'Be unsuitable for a particular employer',
      ]),
      p('You are responsible for reviewing all generated content before using or submitting it.'),
    ]),
    section('13', '13. Accuracy of Your CV', [
      p('You are responsible for ensuring that information submitted to employers is truthful.'),
      p('You may not knowingly use FlacronCV to fabricate or misrepresent:'),
      ul([
        'Education',
        'Employment',
        'Certifications',
        'Licenses',
        'Skills',
        'Experience',
        'Achievements',
        'Awards',
        'References',
        'Qualifications',
        'Identity',
      ]),
      p(
        'FlacronCV may assist with wording, organization, presentation, and suggestions, but you remain responsible for factual accuracy.',
      ),
    ]),
    section('14', '14. User Content', [
      p('You retain ownership of content that you lawfully submit to FlacronCV.'),
      p(
        'You grant Flacron Enterprises a limited right to host, store, transmit, process, reproduce, and otherwise use submitted content as reasonably necessary to:',
      ),
      ul([
        'Provide the requested service',
        'Generate requested outputs',
        'Save documents',
        'Export documents',
        'Maintain the platform',
        'Secure the platform',
        'Comply with applicable law',
      ]),
      p('You represent that you have appropriate rights to material you upload.'),
    ]),
    section('15', '15. Generated Content', [
      p(
        'Subject to applicable law, third-party rights, and these Terms, users may use outputs generated for them through FlacronCV.',
      ),
      p('You remain responsible for:'),
      ul([
        'Reviewing generated content',
        'Checking factual accuracy',
        'Verifying dates',
        'Verifying qualifications',
        'Avoiding plagiarism',
        'Avoiding misrepresentation',
        'Complying with employer requirements',
        'Complying with applicable law',
      ]),
    ]),
    section('16', '16. Job Descriptions and Third-Party Content', [
      p(
        'If you submit a job description or other third-party material, you represent that your use of that material is lawful.',
      ),
      p(
        'FlacronCV may process such content only as reasonably necessary to provide requested functionality.',
      ),
    ]),
    section('17', '17. Templates', [
      p(
        'FlacronCV templates, designs, layouts, interface components, and related platform materials may be protected by intellectual-property laws.',
      ),
      p(
        'Your use of a generated CV does not transfer ownership of the underlying FlacronCV software, template system, brand assets, or platform technology.',
      ),
    ]),
    section('18', '18. Prohibited Uses', [
      p('You may not use FlacronCV to:'),
      ul([
        'Commit fraud',
        'Misrepresent qualifications',
        'Impersonate another person',
        'Violate applicable law',
        'Circumvent Free Plan restrictions',
        'Circumvent subscription limits',
        'Circumvent AI-credit limits',
        'Circumvent export limits',
        "Access another user's documents",
        'Attempt unauthorized access',
        'Attack the service',
        'Introduce malware',
        'Upload harmful files',
        'Scrape the service without authorization',
        'Reverse engineer protected service components where prohibited',
        'Interfere with other users',
        'Infringe intellectual-property rights',
        'Violate privacy rights',
        'Abuse APIs',
        'Automate account creation for improper purposes',
      ]),
    ]),
    section('19', '19. Intellectual Property', [
      p('FlacronCV and associated:'),
      ul([
        'Software',
        'Logos',
        'Designs',
        'Templates',
        'Interfaces',
        'Technology',
        'Branding',
        'Trademarks',
        'Platform content',
      ]),
      p(
        'are owned by, licensed to, or otherwise lawfully used by Flacron Enterprises except where otherwise identified.',
      ),
      p('Flacron Engine and related branding may also be proprietary assets of Flacron Enterprises.'),
    ]),
    section('20', '20. Third-Party Services', [
      p('FlacronCV may rely on third-party services for:'),
      ul([
        'AI processing',
        'Hosting',
        'Authentication',
        'Payments',
        'Analytics',
        'Email',
        'Error monitoring',
        'Security',
        'File storage',
      ]),
      p('Flacron Enterprises does not guarantee that independent third-party services will always be:'),
      ul(['Available', 'Accurate', 'Error-free', 'Secure', 'Uninterrupted']),
    ]),
    section('21', '21. Service Availability', [
      p('We may:'),
      ul([
        'Modify features',
        'Add features',
        'Remove features',
        'Modify plan limits',
        'Perform maintenance',
        'Suspend features',
        'Restrict abusive usage',
        'Update AI providers',
        'Update templates',
      ]),
      p('We do not guarantee uninterrupted availability.'),
    ]),
    section('22', '22. Suspension and Termination', [
      p('We may suspend or terminate accounts where reasonably necessary because of:'),
      ul([
        'Fraud',
        'Free Plan abuse',
        'Trial abuse',
        'Payment failure',
        'Security concerns',
        'Illegal activity',
        'Terms violations',
        'Unauthorized access attempts',
        'Platform abuse',
        'Misuse of infrastructure',
      ]),
    ]),
    section('23', '23. Disclaimer of Warranties', [
      p('To the fullest extent permitted by applicable law, FlacronCV is provided on an:'),
      p('\u201cAS IS\u201d and \u201cAS AVAILABLE\u201d'),
      p('basis.'),
      p('We do not guarantee that:'),
      ul([
        'AI outputs will be accurate',
        'ATS scores will match employer systems',
        'Templates will be accepted by every employer',
        'A CV will obtain interviews',
        'A Cover Letter will obtain responses',
        'A job application will be successful',
        'The service will always be uninterrupted or error-free',
      ]),
    ]),
    section('24', '24. Limitation of Liability', [
      p(
        'To the fullest extent permitted by applicable law, Flacron Enterprises, FlacronCV, and their affiliates, officers, employees, contractors, and service providers will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages arising from use of or inability to use FlacronCV.',
      ),
      p('This may include losses relating to:'),
      ul([
        'Employment opportunities',
        'Missed interviews',
        'Hiring decisions',
        'Salary opportunities',
        'AI-generated errors',
        'ATS scoring',
        'Document-formatting issues',
        'Third-party service failures',
        'Data loss',
        'Employer decisions',
      ]),
      p('Nothing in these Terms excludes liability that cannot lawfully be excluded.'),
    ]),
    section('25', '25. Indemnification', [
      p(
        'To the extent permitted by applicable law, you agree to indemnify and hold harmless Flacron Enterprises from claims, liabilities, damages, and expenses arising from:',
      ),
      ul([
        'Your unlawful use of FlacronCV',
        'Your violation of these Terms',
        'Your infringement of third-party rights',
        'False information you knowingly submit or publish',
        'Content you unlawfully upload',
      ]),
    ]),
    section('26', '26. Changes to These Terms', [
      p('We may update these Terms periodically.'),
      p('The updated version will display a revised Last Updated date.'),
      p('Material changes may be communicated through:'),
      ul(['Email', 'Website notice', 'Application notification', 'Legal acceptance popup']),
      p('Where appropriate, users may be required to acknowledge materially updated Terms.'),
    ]),
    section('27', '27. Governing Law', [
      p(
        'These Terms and disputes arising from or relating to FlacronCV will be governed by the laws of the State of New York, United States, without regard to conflict-of-law principles, except where mandatory consumer-protection law provides otherwise.',
      ),
    ]),
    section('28', '28. Severability', [
      p(
        'If any provision of these Terms is found unenforceable, the remaining provisions will continue in effect to the extent permitted by law.',
      ),
    ]),
    section('29', '29. Entire Agreement', [
      p(
        'These Terms, together with policies referenced within them, constitute the agreement governing your use of FlacronCV unless another written agreement applies.',
      ),
    ]),
    section('30', '30. Contact', [
      p('Questions concerning these Terms may be submitted to:'),
      p('FlacronCV'),
      p('Operated by Flacron Enterprises'),
      p('410 E 95th St'),
      p('Brooklyn, NY 11212'),
      p('United States'),
      p('Phone: 929-990-1182'),
      p('FlacronCV Email: contact@flacroncv.com'),
      p('Parent Company Email: Contact@flacronenterprises.com'),
      p('Powered by Flacron Engine'),
    ]),
  ],
};
