import { NestFactory } from '@nestjs/core';
import { ValidationPipe } from '@nestjs/common';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import helmet from 'helmet';
import { AppModule } from './app.module';
import { AllExceptionsFilter } from './common/filters/all-exceptions.filter';
import { TransformInterceptor } from './common/interceptors/transform.interceptor';
import { LoggingInterceptor } from './common/interceptors/logging.interceptor';

function validateEnv() {
  const required = [
    'FIREBASE_PROJECT_ID',
    'FIREBASE_PRIVATE_KEY',
    'FIREBASE_CLIENT_EMAIL',
    'FIREBASE_STORAGE_BUCKET',
    'STRIPE_SECRET_KEY',
    'STRIPE_WEBHOOK_SECRET',
  ];
  const missing = required.filter((key) => !process.env[key]);
  if (missing.length > 0) {
    throw new Error(`Missing required environment variables: ${missing.join(', ')}`);
  }
}

/**
 * The Stripe webhook-secret boot diagnostic that used to live here has been
 * removed. It ran unconditionally on every start and printed the secret's
 * length, its first six AND last six characters, and a SHA-256 prefix — real
 * key material written into Render's log store on every deploy and restart.
 * Its job is done by `apps/api/scripts/which-webhook-secret.mjs`, which is run
 * deliberately by a developer instead of by the production process.
 */
async function bootstrap() {
  validateEnv();

  const isProduction = process.env.NODE_ENV === 'production';

  const app = await NestFactory.create(AppModule, {
    rawBody: true,
  });

  // Behind Render's proxy the client IP arrives in X-Forwarded-For. Without
  // trust proxy, rate limiting would key every request to the proxy's IP and
  // all users would share a single throttle bucket.
  app.getHttpAdapter().getInstance().set('trust proxy', 1);

  app.use(helmet());

  // CORS configuration - dynamically validate origins
  const frontendUrl = process.env.FRONTEND_URL?.replace(/\/$/, '');
  const extraOrigins = (process.env.ADDITIONAL_ORIGINS ?? '')
    .split(',')
    .map((o) => o.trim().replace(/\/$/, ''))
    .filter(Boolean);

  // localhost is a DEV convenience and must not be trusted in production. With
  // `credentials: true`, keeping it meant anything a victim ran on their own
  // machine at :3000/:3001 could make credentialed cross-origin calls to the
  // live API and read the response. In production only the configured frontend
  // and ADDITIONAL_ORIGINS are allowed.
  const allowedOrigins = [
    ...(isProduction ? [] : ['http://localhost:3000', 'http://localhost:3001']),
    frontendUrl,
    ...extraOrigins,
  ].filter(Boolean) as string[];

  if (allowedOrigins.length === 0) {
    // Fail loudly rather than starting an API no browser can talk to.
    throw new Error('No CORS origins configured — set FRONTEND_URL (and ADDITIONAL_ORIGINS if needed).');
  }

  app.enableCors({
    origin: (origin, callback) => {
      // Allow requests with no origin (like mobile apps or Postman)
      if (!origin) {
        return callback(null, true);
      }

      // Normalize origin by removing trailing slash
      const normalizedOrigin = origin.replace(/\/$/, '');

      // Check if normalized origin is in allowed list
      const isAllowed = allowedOrigins.some(
        (allowed) => allowed === normalizedOrigin || `${allowed}/` === origin
      );

      if (isAllowed) {
        callback(null, true);
        return;
      }

      // Deny by omitting the CORS header, do NOT throw. Throwing surfaced as a
      // 500 (verified), so every probe from an unlisted origin looked like a
      // server fault in the logs and in error tracking — noise that masks real
      // failures, and trivially generated by anyone. The browser still blocks
      // the response either way; this just reports it honestly.
      callback(null, false);
    },
    credentials: true,
    methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
    allowedHeaders: ['Content-Type', 'Authorization', 'Accept-Language'],
  });

  app.setGlobalPrefix('api/v1');

  app.useGlobalPipes(
    new ValidationPipe({
      whitelist: true,
      transform: true,
      forbidNonWhitelisted: true,
      transformOptions: { enableImplicitConversion: true },
    }),
  );

  app.useGlobalFilters(new AllExceptionsFilter());
  app.useGlobalInterceptors(new TransformInterceptor(), new LoggingInterceptor());

  // Swagger is a DEVELOPMENT tool. Served unconditionally it published the
  // entire API surface — every route, parameter and DTO shape — to anonymous
  // callers in production (verified: GET /api/docs and /api/docs-json both
  // returned 200). That is free reconnaissance for anyone probing the service.
  if (!isProduction) {
    const config = new DocumentBuilder()
      .setTitle('FlacronCV API')
      .setDescription('AI-powered CV & Cover Letter Builder API')
      .setVersion('1.0')
      .addBearerAuth()
      .addTag('auth')
      .addTag('users')
      .addTag('cvs')
      .addTag('cover-letters')
      .addTag('ai')
      .addTag('templates')
      .addTag('payments')
      .addTag('support')
      .addTag('admin')
      .build();

    const document = SwaggerModule.createDocument(app, config);
    SwaggerModule.setup('api/docs', app, document);
  }

  // Health check (bypasses global prefix so load balancers can reach /health)
  const httpAdapter = app.getHttpAdapter();
  httpAdapter.get('/health', (_req: unknown, res: { json: (body: unknown) => void }) => {
    res.json({ status: 'ok', timestamp: new Date().toISOString() });
  });

  const port = process.env.PORT || 4000;
  await app.listen(port);
  console.log(`FlacronCV API running on http://localhost:${port}`);
  // Only advertise the docs when they are actually mounted — printing this in
  // production pointed at a route that now 404s.
  if (!isProduction) {
    console.log(`Swagger docs at http://localhost:${port}/api/docs`);
  }
}
bootstrap();
