name: Setting Page Multi-Browser Tests

on:
  push:
    branches:
      - web-templatesPage-test

jobs:
  setting-page-cross-browser:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, edge, firefox]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        working-directory: web-automation
        run: npm install

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: web-automation
          browser: ${{ matrix.browser }}
          headed: true
          command: npm run test:templatesPage-test

      - name: Upload Mochawesome Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: setting page multi-browser-${{ matrix.browser }}-report
          path: web-automation/cypress/reports/html
